### ISSUE TITLE
Any chance it will ever support adding or removing checks?

### ISSUE THREAD

**Issue by NeckBeardPrince** [sensu-plugins/sensu-plugins-pingdom#1]

**Comment by mattyjones** [comment]
@NeckBeardPrince  What do you mean?  Can you please be more specific?

Thanks.

**Comment by NeckBeardPrince** [comment]
From what I understand the plugin cannot create new checks, correct?

**Comment by mattyjones** [comment]
@NeckBeardPrince  You can create a new check for this plugin if you would like.  You would just need to write it and then submit a Pull Request.  Is this what you are referring to?
